name:                tetris
version:             0.1.0.0
license:             BSD3
author:              "TDA555/DIT440 Introduction to Functional Programming"
maintainer:          "alexg@chalmers.se"
copyright:           "2020 Chalmers - Göteborgs Universitet"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- ansi-terminal
- base >= 4.7 && < 5
- codeworld-api 
- directory
- QuickCheck
- random
- text

library:
  source-dirs: src

executables:
  tetris-exe:
    main:                Tetris.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tetris

tests:
  tetris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tetris
